//
// Test Bench Module Project_lib.Num_Of_Errors_tb.Num_Of_Errors_tester
//
// Created:
//          by - benmaorr.refael,kapelnik.Tal (L330W509)
//          at - 14:55:47 11/22/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module Num_Of_Errors_tb;

// Local declarations
parameter DATA_WIDTH = 32;
parameter AMBA_ADDR_WIDTH = 32;
parameter AMBA_WORD = 32;

// Internal signal declarations
logic clk = 1'b0;
logic [5:0] Yin;
logic [5:0] DATA_IN;
logic       Small;
logic       Medium;
logic [1:0] NOF; /// out
logic [4:0] OUT; /// out


Num_Of_Errors #(32,32,32) U_0(
   .clk            (clk),
   .Yin            (Yin),
   .DATA_IN        (DATA_IN),
   .Small          (Small),
   .Medium         (Medium),
   .NOF            (NOF),
   .OUT            (OUT)
);
always
#1 clk <=~clk;

initial begin
#10
Small <= 1'b1;
Medium <= 1'b0;

#2; // No errors 
Yin <= 6'b101100;
DATA_IN <= 6'b101100;
$display("NOF =%0b ",NOF);

#6; // 1 erorr
Yin <= 6'b101100;
DATA_IN <= 6'b010000;
$display("NOF =%0b ",NOF);

#6;// 2 error
Yin <= 6'b101100;
DATA_IN <= 6'b001010;
$display(" NOF =%0b ",NOF);

#6;// 0 error
Yin <= 6'b101100;
DATA_IN <= 6'b001100;
$display("NOF =%0b ",NOF);

#6;// 2 error
Yin <= 6'b100000;
DATA_IN <= 6'b000110;
$display(" NOF =%0b ",NOF);

#6;// 2 error
Yin <= 6'b101000;
DATA_IN <= 6'b001110;
$display(" NOF =%0b ",NOF);

#100
$finish(0);
end

endmodule // Num_Of_Errors_tb


