//
// Test Bench Module ENCDEC_lib.Encoder_tb.Encoder_tester
//
// Created:
//          by - benmaorr.refael,kapelnik.Tal (L330W509)
//          at - 15:11:13 11/18/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module Encoder_tb;

// Local declarations
parameter DATA_WIDTH = 32;
parameter AMBA_ADDR_WIDTH = 32;
parameter AMBA_WORD = 32;

// Internal signal declarations
logic                   clk=1'b0;
logic                   rst=1'b0;
reg  [AMBA_WORD - 1:0] DATA_IN;
reg  [1:0]             CODEWORD_WIDTH =2'b00;
wire [AMBA_WORD - 1:0] OUT;


Encoder #(32,32,32) U_0(
   .clk            (clk),
   .rst            (rst),
   .DATA_IN        (DATA_IN),
   .CODEWORD_WIDTH (CODEWORD_WIDTH),
   .OUT              (OUT)
);

//clock always block:
always
#1 clk <=~clk;

initial begin
#10.2ns;  //asyncrounsly de-assert asrtn
rst <= 1'b0;
#10;
@(posedge clk) rst <= 1'b1;

#2;
CODEWORD_WIDTH<= 2'b00 ;
DATA_IN<=     {{4{1'b1}},{AMBA_WORD-4{1'b0}}};

#6;
CODEWORD_WIDTH<= 2'b01 ;
DATA_IN<=     {{11{1'b1}},{AMBA_WORD-11{1'b0}}};

#6;
CODEWORD_WIDTH<= 2'b10 ;
DATA_IN<=     {{26{1'b1}},{AMBA_WORD-26{1'b0}}};

#100
$finish(0);
end

endmodule